# This is a jenkins trigger workflow 

name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: deepkumar/my-project@main
      with:
        url: "https://vmax-jenkins01.cec.lab.emc.com/job/test_external_repo/"
        user: "svc_vmaxjenkins"
        token: "2cb9ad410703bb5d30bd42cd8ab15da257c9dacad9d5d217dc8ef0c2cfaaf829"
        job: "test_external_repo"
